# Generated by Django 4.0.4 on 2022-05-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_slot_slotsize_alter_slot_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='doctor_name',
            new_name='doctor_id',
        ),
    ]
