# Generated by Django 4.0.4 on 2022-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_doctor_id_slot_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
