# Generated by Django 4.0.4 on 2022-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
