# Generated by Django 4.0.4 on 2022-05-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.CharField(max_length=50),
        ),
    ]
