# Generated by Django 4.0.4 on 2022-05-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_slot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.CharField(choices=[(0, '09:00 am To 10:00 am'), ('10:00 am TO 11:00 am', '10:00 am TO 11:00 am'), (2, '11:00 am To 12:00 am'), (3, '12:00 am To 01:00 pm'), (4, '02:00 pm To 03:00 pm'), (5, '03:00 pm To 04:00 pm'), (6, '04:00 pm To 05:00 pm')], max_length=50),
        ),
    ]
