# Generated by Django 4.0.4 on 2022-05-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_slot_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='weeks',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
