# Generated by Django 4.0.4 on 2022-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_slot_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
