# Generated by Django 4.0.4 on 2022-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_appointment_user_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(default='profile.png', upload_to='user'),
        ),
    ]
