# Generated by Django 4.0.4 on 2022-05-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, default='profile.png', null=True, upload_to='user'),
        ),
    ]
