# Generated by Django 4.0.4 on 2022-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Absent'), (3, 'Canceled')], default=0),
        ),
    ]
