# Generated by Django 4.0.4 on 2022-05-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_appointment_status_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='doctor_name',
            new_name='doctor_id',
        ),
    ]
