# Generated by Django 4.0.4 on 2022-05-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_doctor_name_slot_doctor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doc',
        ),
    ]
